### Get Event by ID with Variable
@baseUrl = http://localhost:8080

@eventID = 8beff8fd-39e4-49ea-ae5e-a0ec9af888c5

### Listar todos os Events 
GET {{baseUrl}}/events

### Listar Event por ID
GET {{baseUrl}}/events/{{eventID}}

### Listar Spots por id Event 
GET {{baseUrl}}/events/{{eventID}}/spots

### Criar Spots por id
POST {{baseUrl}}/events/{{eventID}}/spots
Content-Type: application/json
Accept: application/json

{
  "number_of_spots": 5
}

### Buy Tickets for an Event for PARTNER
POST {{baseUrl}}/checkout
Content-Type: application/json
Accept: application/json

{
  "event_id": "8beff8fd-39e4-49ea-ae5e-a0ec9af888c5",
  "card_hash": "809kh",
  "ticket_kind": "half",
  "spots": [ "A5", "B5" ],
  "email": "test@test.com"
}

### Criar evento
POST {{baseUrl}}/event
Content-Type: application/json
Accept: application/json

{
  "name":"Event 005 - Partner1",
  "location": "São Paulo, SP",
  "organization": "Partner 1",
  "rating": "L14",
  "date": "2024-10-10T04:12:05Z",
  "image_url": "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
  "capacity": 10,
  "price": 100,
  "partner_id": 1
}

